# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: scm/postgres
    build: ./sql
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env

  cli:
    image: scm/cli
    build: .

volumes:
  pgdata:
