# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_USER: okay
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    secrets:
      - db_password

secrets:
   db_password:
     file: db.secrets.txt
    
volumes:
  pgdata:
