name: Scala CI

on:
  push:
    branches:
        - master
        - dev
  pull_request:
    branches:
        - master
        - dev

jobs:
  scalatest_sbt:
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.0.0
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Formatting
  #     run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
